name: Build Mac
on:
  - push
permissions: {}
jobs:
  CI:
    permissions:
      contents: write # for npx prebuild to make release
    name: Node.js ${{ matrix.nodejs_version }} ${{ matrix.nodejs_arch }}
    runs-on: macos-m1
    strategy:
      fail-fast: false
      matrix:
        include:
          - nodejs_version: 14
            nodejs_arch: x64
          - nodejs_version: 18
            nodejs_arch: arm64
    defaults:
      run:
        shell: /usr/bin/arch -arch arm64e /bin/bash -l {0}
    steps:
      - name: Dependencies (Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs_version }}
          architecture: ${{ matrix.nodejs_arch }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and build
        run: SKIP_PREBUILT=yes yarn install
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: package/*.tar.gz
